services:
  postgres:
    image: postgres:18-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${INIT_DB}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql:rw

  redis:
    image: redis:8-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - cache:/data

volumes:
  pgdata:
  cache:
